project_name: sqpr
before:
  hooks:
    - go mod tidy
builds:
  - binary: sqpr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  skip: true
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "herlon214/sonarqube-pr-issues:latest"
      - "herlon214/sonarqube-pr-issues:{{ .Tag }}"
      - "herlon214/sonarqube-pr-issues:v{{ .Major }}"